### ISSUE TITLE
Unknown Database Error

### ISSUE THREAD

**Issue by alistair-hmh** [hmhco/vagrant-common#2]
@lcymbura, after I follow your steps for RI, I run:

```shell
mvn clean package -Dspring.profiles.active=local spring-boot:run
```

Then I see the following error:

```shell
[ERROR] Message    : Unknown database 'reading_inventory'
```

![screen shot 2019-01-11 at 1 17 35 pm](https://user-images.githubusercontent.com/38665769/51051954-4865e280-15a3-11e9-8703-64257488f69f.png)

`ansible/roles/mysql/defaults/main.yml`

```yml
# Databases.
mysql_databases:
  - name: reading_inventory
    collation: latin1_swedish_ci
    encoding: latin1
```

It does not seem like the database is getting built.

Any ideas what could be going on here?
